AWSTemplateFormatVersion: '2010-09-09'
Description: EC2 instance + Elastic IP + EC2 Role with policy to manage S3 bucket
Mappings:
  AWSRegionUbuntu2AMI:
    eu-central-1:
      AmiId: ami-26c43149
    eu-west-1:
      AmiId: ami-ed82e39e
Parameters:
  ProjectName:
    Type: String
  Region:
    Type: String
  EC2VolumeSize:
    Type: Number
    Description: EBS Volume Size (data) to be attached to application node in GBs
    MaxValue: '10'
    MinValue: '8'
  EC2InstanceType:
    Type: String
    AllowedValues:
    - t2.micro
    Description: EC2 HVM instance type.
    ConstraintDescription: Must be a valid EC2 HVM instance type.
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Name of an existing EC2 KeyPair. EC2 instances will launch with this
      KeyPair.
  S3BucketName:
    Type: String
    Description: Name of S3 bucket to manage
    AllowedPattern: ^[a-z0-9][a-z0-9-.]*$
Resources:
  EC2:
    Type: AWS::EC2::Instance
    Properties:
      BlockDeviceMappings:
      - DeviceName: /dev/sda1
        Ebs:
          DeleteOnTermination: 'true'
          VolumeSize:
            Ref: EC2VolumeSize
          VolumeType: gp2
      IamInstanceProfile:
        Ref: InstanceProfile
      ImageId:
        Fn::FindInMap:
        - AWSRegionUbuntu2AMI
        - Ref: AWS::Region
        - AmiId
      InstanceType:
        Ref: EC2InstanceType
      SecurityGroups:
      - Fn::ImportValue: !Sub '${ProjectName}-EC2SecurityGroup'
      KeyName:
        Ref: KeyName
      Tags:
      - Key: Name
        Value:
          Ref: ProjectName
  EIP:
    Type: AWS::EC2::EIP
    Properties:
      InstanceId:
        Ref: EC2
  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
      - Ref: InstanceRole
  InstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action:
          - sts:AssumeRole
          Effect: Allow
          Principal:
            Service:
            - ec2.amazonaws.com
        Version: '2012-10-17'
      Path: /
      Policies:
      - PolicyDocument:
          Statement:
          - Action: '*'
            Effect: Allow
            Resource:
              - Fn::Join:
                - ''
                - - 'arn:aws:s3:::'
                  - Ref: S3BucketName
                  - /*
              - Fn::Join:
                - ''
                - - 'arn:aws:s3:::'
                  - Ref: S3BucketName
          - Action: 's3:ListAllMyBuckets'
            Effect: Allow
            Resource: '*'
          Version: '2012-10-17'
        PolicyName:
          Fn::Join:
          - '-'
          - - Ref: ProjectName
            - S3
Outputs:
  ElasticIp:
    Value:
      Ref: EIP
    Export:
      Name: !Sub '${ProjectName}-EIP'
