AWSTemplateFormatVersion: '2010-09-09'
Description: EC2Security Group
Parameters:
  ProjectName:
    Type: String
Resources:
  EC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Sub '${ProjectName}-EC2SecurityGroup'
      SecurityGroupIngress:
      - CidrIp: 0.0.0.0/0
        FromPort: '80'
        IpProtocol: tcp
        ToPort: '80'
      - CidrIp: 0.0.0.0/0
        FromPort: '443'
        IpProtocol: tcp
        ToPort: '443'
      - CidrIp: 0.0.0.0/0
        FromPort: '22'
        IpProtocol: tcp
        ToPort: '22'
      Tags:
      - Key: Name
        Value:
          Ref: ProjectName
Outputs:
  EC2SecurityGroup:
    Value:
      Ref: EC2SecurityGroup
    Export:
      Name: !Sub '${ProjectName}-EC2SecurityGroup'
