AWSTemplateFormatVersion: '2010-09-09'
Description: Route53 RecordSet
Parameters:
  HostedZoneName:
    Type: String
  Route53RecordSetName:
    Type: String
  Route53RecordSetType:
    Type: String
    AllowedValues:
      - A
      - AAAA
      - CNAME
      - MX
      - NS
      - PTR
      - SOA
      - SPF
      - SRV
      - TXT
  IP:
    Type: String
    Default: None
  CloudFormationAliasTarget:
    Type: String
    Default: None
Conditions:
  CloudFrontDistributionPresent: !Not [!Equals [ !Ref CloudFormationAliasTarget, None ]]
  InstanceIPPresent: !Not [!Equals [ !Ref IP, None ]]
Resources:
  Route53RecordSet:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName:
        !Sub '${HostedZoneName}.'
      Name:
        Ref: Route53RecordSetName
      Type:
        Ref: Route53RecordSetType
      ResourceRecords:
        !If [
            InstanceIPPresent,
            [Ref: IP],
            Ref: 'AWS::NoValue'
        ]
      TTL:
        !If [
          InstanceIPPresent,
          '300',
          Ref: 'AWS::NoValue'
        ]
      AliasTarget:
        !If [
          CloudFrontDistributionPresent,
          {
            DNSName: !Sub '${CloudFormationAliasTarget}',
            # see: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-route53-aliastarget.html
            HostedZoneId: 'Z2FDTNDATAQYW2',
          },
          Ref: 'AWS::NoValue'
        ]
Outputs:
  Route53RecordSet:
    Value:
      Ref: Route53RecordSet
