---
- name: Disable the default site
  sudo_user: root
  file: path={{nginx_conf_dir}}/sites-enabled/default state=absent
  notify:
  - reload nginx

- name: Remove the default configuration
  sudo_user: root
  file: path={{nginx_conf_dir}}/conf.d/default.conf state=absent
  notify:
  - reload nginx
