---
- name: Install app packages
  sudo_user: root
  apt: pkg={{ item }} state=latest update_cache=yes
  with_items: default_packages
  when: default_packages|length > 0

- name: Install additional packages
  sudo_user: root
  apt: pkg={{ item }} state=latest update_cache=yes
  with_items: additional_packages
  when: additional_packages|length > 0
